apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-seed
  labels:
    app: tier1-galera-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-seed
  template:
    metadata:
      labels:
        app: tier1-galera-seed
    spec:
      containers:
      - name: tier1-galera-seed
        image: idstudios/mariadb-galera-docker:10.1
        args: ["seed"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: Fender2000
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: Fender2000
        - name: MYSQL_ROOT_PASSWORD
          value: Fender2000
        - name: MYSQL_DATABASE
          value: drupaldb
        - name: NODE_ADDRESS
          value: eth0
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-seed-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: tier1-galera-seed-volume
        persistentVolumeClaim:
          claimName: tier1-galera-seed-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-seed
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-seed