#!/bin/bash

echo -n "Enter repo URL (eg. docker.example.com): "
read REPO

echo -n "Enter user account: "
read  REPO_USER

echo -n "Enter user password: "
read -s PASSWORD
echo

AUTH_URL=https://$REPO

# obtain a JSON token, and extract the "token" value using 'jq'
TOKEN=$(curl -s -u "${REPO_USER}:${PASSWORD}" "${AUTH_URL}?scope=repository:${REPO}:pull&service=registry.docker.io" | jq -r ".token")
HEADER=$(echo "{\"registrytoken\":\"${TOKEN}\"}"|base64 )

echo "Enter the following in your ~/.docker/config.json:"
echo

echo "\"HttpHeaders\": { \"X-Registry-Auth\": \"${HEADER}\" }"
echo
