#!/bin/bash

export DB_CONFIG=./deploys/$1
if [ ! -f $DB_CONFIG ]; then 
  echo "The galera yml config file was unspecified or not found in the 'deploys' folder."
  return
fi

export STACK_NAME=`sed -n '/^stack-name:/ {s///p;q;}' $DB_CONFIG | xargs`
if [ -z $STACK_NAME ]; then 
  echo "No stack name specified! Stack name is required."
  return
fi

export GALERA_TAG=`sed -n '/^galera-version:/ {s///p;q;}' $DB_CONFIG | xargs`
[ -z $GALERA_TAG ] && GALERA_TAG=latest

export HAPROXY_TAG=`sed -n '/^proxy-version:/ {s///p;q;}' $DB_CONFIG | xargs`
[ -z $HAPROXY_TAG ] && HAPROXY_TAG=latest

export DOCKER_HOST=`sed -n '/^docker-host:/ {s///p;q;}' $DB_CONFIG | xargs`
export DOCKER_CERT_PATH=`sed -n '/^docker-host-cert-path:/ {s///p;q;}' $DB_CONFIG | xargs`
export USE_VDVS=`sed -n '/^use-vdvs:/ {s///p;q;}' $DB_CONFIG | xargs`

if [ "$USE_VDVS" != "true" ]; then
  export GALERA_NODE1=`sed -n '/^galera-node1:/ {s///p;q;}' $DB_CONFIG | xargs`
  export GALERA_NODE2=`sed -n '/^galera-node2:/ {s///p;q;}' $DB_CONFIG | xargs`
  export GALERA_NODE3=`sed -n '/^galera-node3:/ {s///p;q;}' $DB_CONFIG | xargs`
fi

export GALERA_NETWORK=`sed -n '/^galera-network:/ {s///p;q;}' $DB_CONFIG | xargs`
export GALERA_NETWORK_NAME=`sed -n '/^galera-network-name:/ {s///p;q;}' $DB_CONFIG | xargs`

export APP_NETWORK=`sed -n '/^app-network:/ {s///p;q;}' $DB_CONFIG | xargs`
export APP_NETWORK_NAME=`sed -n '/^app-network-name:/ {s///p;q;}' $DB_CONFIG | xargs`
