#!/bin/bash

function show_usage () {
  echo 
  echo "Usage: db-close <galera yml config file>"
  echo 
  echo "Eg: db-close tier1-galera.yml"
  echo 
}

source ./conf $1
if [ $? -ne 0 ]; then
  show_usage
  exit 1
fi
if [ ! -f $WEB_CONFIG ]; then 
  show_usage
  exit 1
fi
if [ -z $STACK_NAME ]; then 
  show_usage
  exit 1
fi

echo
echo "Closing 3306 on the galera haproxy post data load"
./docker-env service update --detach --publish-rm 3306 ${STACK_NAME}_galera-haproxy
sleep 10s
echo -n "Waiting for galera haproxy to restart with 3306 closed..."
while [ "`./docker-env service ls | grep ${STACK_NAME}_galera-haproxy | grep '1/1' | wc -l | xargs`" != "1" ]
do
  echo -n "."
  sleep 2s
done
echo
