#!/bin/bash

function show_usage () {
  echo 
  echo "Usage: db-close <galera yml config file>"
  echo 
  echo "Eg: db-close tier1-galera.yml"
  echo 
}

source ./conf $1
if [ $? -ne 0 ]; then
  show_usage
  exit 1
fi
if [ ! -f $WEB_CONFIG ]; then 
  show_usage
  exit 1
fi
if [ -z $STACK_NAME ]; then 
  show_usage
  exit 1
fi

echo
echo "Closing 3306 on the galera haproxy post data load"
./docker-env service update --detach --publish-rm 3306 ${STACK_NAME}_galera-haproxy
echo "Waiting 10s for galera haproxy to reload"
sleep 10s
echo