#!/bin/bash

function show_usage () {
  echo 
  echo "Usage: db-open <stack name> <galera yml config file>"
  echo 
  echo "Eg: db-open tier1 tier1-galera.yml"
  echo 
}

source ./conf $1 $2
if [ $? -ne 0 ]; then
  show_usage
  exit 1
fi

echo
echo "Exposing 3306 on the galera haproxy for data load"
./docker-env service update --detach --publish-add 3306:3306 ${STACK_NAME}_galera-haproxy
echo "Waiting 30s for galera haproxy to reload"
sleep 30s

DB_HOST=`echo $DOCKER_HOST | sed 's/:.*//'`

echo
echo "Galera WSREP Cluster Info:"
echo "--------------------------"
mysql -h $DB_HOST  -u root --password=`cat .secrets/mysql_root_password` < util/cluster-info.sql
if [ $? -ne 0 ]; then
  echo
  echo "Failure deploying mariadb galera!"
  echo
else
  echo
  echo "MariaDB Galera Cluster: ${STACK_NAME} Successfully opened for data loading!"
  echo
fi
