
- hosts: all
  become: false
  any_errors_fatal: true
  gather_facts: false
  vars:

    galera_cluster_home: "clusters/{{ galera_cluster_name }}"
    
  tasks:

  - name: Ensure the cluster folder exists
    local_action:
      module: shell
      _raw_params: "if [ ! -d {{ galera_cluster_home }} ]; then mkdir {{ galera_cluster_home }}; fi"
    become: false
    run_once: true
    ignore_errors: true

  - name: Generate the iSCSI based galera volumes manifest
    local_action:
      module: template
      src: templates/galera-volumes.j2
      dest: "{{ galera_cluster_home }}/galera-volumes.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera seed manifest
    local_action:
      module: template
      src: templates/galera-seed.j2
      dest: "{{ galera_cluster_home }}/galera-seed.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera nodes manifest
    local_action:
      module: template
      src: templates/galera-nodes.j2
      dest: "{{ galera_cluster_home }}/galera-nodes.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera haproxy manifest
    local_action:
      module: template
      src: templates/galera-haproxy.j2
      dest: "{{ galera_cluster_home }}/galera-haproxy.yml"
      mode: 0766
    run_once: true
    become: false

  - name: Generate the galera external access manifest
    local_action:
      module: template
      src: templates/galera-external-access.j2
      dest: "{{ galera_cluster_home }}/galera-external-access.yml"
      mode: 0766
    run_once: true
    become: false
    