apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-node1
  labels:
    app: tier1-galera-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-node1
  template:
    metadata:
      labels:
        app: tier1-galera-node1
    spec:
      containers:
      - name: tier1-galera-node1
        image: idstudios/mariadb-galera-docker:10.1
        args: ["node", "tier1-galera-seed,tier1-galera-node2,tier1-galera-node3,tier1-galera-node4,tier1-galera-node5"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: "Fender2000"
        - name: NODE_ADDRESS
          value: "eth0"
        - name: HEALTHY_WHILE_BOOTING
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-node1-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: tier1-galera-node1-volume
        persistentVolumeClaim:
          claimName: tier1-galera-node1-volume-claim
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-node2
  labels:
    app: tier1-galera-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-node2
  template:
    metadata:
      labels:
        app: tier1-galera-node2
    spec:
      containers:
      - name: tier1-galera-node2
        image: idstudios/mariadb-galera-docker:10.1
        args: ["node", "tier1-galera-seed,tier1-galera-node1,tier1-galera-node3,tier1-galera-node4,tier1-galera-node5"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: "Fender2000"
        - name: NODE_ADDRESS
          value: "eth0"
        - name: HEALTHY_WHILE_BOOTING
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-node2-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: tier1-galera-node2-volume
        persistentVolumeClaim:
          claimName: tier1-galera-node2-volume-claim
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-node3
  labels:
    app: tier1-galera-node3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-node3
  template:
    metadata:
      labels:
        app: tier1-galera-node3
    spec:
      containers:
      - name: tier1-galera-node3
        image: idstudios/mariadb-galera-docker:10.1
        args: ["node", "tier1-galera-seed,tier1-galera-node1,tier1-galera-node2,tier1-galera-node4,tier1-galera-node5"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: "Fender2000"
        - name: NODE_ADDRESS
          value: "eth0"
        - name: HEALTHY_WHILE_BOOTING
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-node3-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: tier1-galera-node3-volume
        persistentVolumeClaim:
          claimName: tier1-galera-node3-volume-claim
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-node4
  labels:
    app: tier1-galera-node4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-node4
  template:
    metadata:
      labels:
        app: tier1-galera-node4
    spec:
      containers:
      - name: tier1-galera-node4
        image: idstudios/mariadb-galera-docker:10.1
        args: ["node", "tier1-galera-seed,tier1-galera-node1,tier1-galera-node2,tier1-galera-node3,tier1-galera-node5"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: "Fender2000"
        - name: NODE_ADDRESS
          value: "eth0"
        - name: HEALTHY_WHILE_BOOTING
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-node4-volume
            mountPath: "/var/lib/mysql"
      volumes:
      - name: tier1-galera-node4-volume
        persistentVolumeClaim:
          claimName: tier1-galera-node4-volume-claim
---
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: tier1-galera-node5
  labels:
    app: tier1-galera-node5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tier1-galera-node5
  template:
    metadata:
      labels:
        app: tier1-galera-node5
    spec:
      volumes:
      - name: tier1-galera-node5-volume
        persistentVolumeClaim:
          claimName: tier1-galera-node5-volume-claim

      containers:
      - name: tier1-galera-node5
        image: idstudios/mariadb-galera-docker:10.1
        args: ["node", "tier1-galera-seed,tier1-galera-node1,tier1-galera-node2,tier1-galera-node3,tier1-galera-node4"]
        env:
        - name: XTRABACKUP_PASSWORD
          value: "Fender2000"
        - name: NODE_ADDRESS
          value: "eth0"
        - name: HEALTHY_WHILE_BOOTING
          value: "1"
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10        
        ports:
        - containerPort: 3306
        - containerPort: 4444
        - containerPort: 4567
        - containerPort: 4567
          protocol: UDP
        - containerPort: 4568
        - containerPort: 8080
        - containerPort: 8081
        volumeMounts:
          - name: tier1-galera-node5-volume
            mountPath: "/var/lib/mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-node1
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-node1
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-node2
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-node2
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-node3
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-node3
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-node4
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-node4
---
apiVersion: v1
kind: Service
metadata:
  name: tier1-galera-node5
spec:
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
  - port: 4444
    name: galera4444
    protocol: TCP
  - port: 4567
    name: galera4567
    protocol: TCP
  - port: 4567
    name: galera4567udp
    protocol: UDP
  - port: 4568
    name: galera4568
    protocol: TCP
  - port: 8080
    name: galera8080
    protocol: TCP
  - port: 8081
    name: galera8081
    protocol: TCP
  selector:
    app: tier1-galera-node5
