#!/bin/bash

DATA_FOLDER=/data
if [ ! -d $DATA_FOLDER/galera_node$1 ]; then
  mkdir -p $DATA_FOLDER/galera_node$1
fi
rm -rf $DATA_FOLDER/galera_node$1/*
echo -n "Galera data volume on host node: `hostname`: ${DATA_FOLDER}/"
ls $DATA_FOLDER
