version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Fender2000
    volumes:
      - mariadb:/var/lib/mysql    

volumes:
  mariadb:
    external: 
      name: mariadb@san
